spring:
  application:
    name: aionys-test-task-api

  h2:
    console:
      enabled: true

  datasource:
    generate-unique-name: false
    name: TestTask

allowed:
  origin: http://localhost:4200

springdoc:
  default-produces-media-type: application/json